config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :dashboards, only: :index

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :profiles
  resources :places
  resources :nights
  resources :games
  resources :bitch_book_entries
  patch "bitch_book_entry/approved/:id", to: "bitch_book_entries#approved", as: :approve_bitch_book_entry
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bitch_book_entry.rb
class BitchBookEntry < ApplicationRecord
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :night
  belongs_to :place
  has_many :players

  def winner
    players.find_by(winner: true)
  end
end

app/models/night.rb
class Night < ApplicationRecord
  belongs_to :user
  belongs_to :place
  has_many :users
  has_many :games
end

app/models/place.rb
class Place < ApplicationRecord
  validates :name, :address, presence: true
  belongs_to :user
  has_many :nights

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def blank_balls
    8 - barkeeper_rating.to_i
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :nights
  has_many :games
  has_many :bitch_book_entries
  has_many :places
  enum role: { player: 0, manager: 1, admin: 2 }

  has_one_attached :avatar

  # after_commit :add_default_avatar, on: %i[create update]

  private

  # def add_default_avatar
  #   return if avatar.attached?

  #   avatar.attach(
  #     io: File.open(
  #       "https://res.cloudinary.com/dk5glvhr6/image/upload/v1678524968/nb-jb/default-avatar_vub2zz.jpg"
  #     ),
  #     filename: 'default-avatar_vub2zz.jpg',
  #     content_type: 'image/jpg'
  #   )
  # end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[avatar first_name last_name birthday first_game sign favorite_drink lucky_number bio wins losses])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar first_name last_name birthday first_game sign favorite_drink lucky_number bio wins losses])
  end
end

app/controllers/bitch_book_entries_controller.rb
class BitchBookEntriesController < ApplicationController
  before_action :set_bitch_book_entry, only: %i[show edit update approved destroy]

  def index
    @bitch_book_entries = BitchBookEntry.all
  end

  def show; end

  def new
    @bitch_book_entry = BitchBookEntry.new
    authorize @bitch_book_entry
  end

  def edit; end

  def create
    @bitch_book_entry = BitchBookEntry.new(bitch_book_entry_params)
    @bitch_book_entry.user = current_user
    if @bitch_book_entry.save!
      redirect_to bitch_book_entries_path
    else
      render :new
    end
  end

  def approved
    @bitch_book_entry.update(approved: true)
    redirect_to bitch_book_entries_path
  end

  def update
    @bitch_book_entry.update(bitch_book_entry_params)
    redirect_to bitch_book_entries_path
  end

  def destroy
    @bitch_book_entry.destroy
    redirect_to bitch_book_entries_path
  end

  private

  def set_bitch_book_entry
    @bitch_book_entry = BitchBookEntry.find(params[:id])
  end

  def bitch_book_entry_params
    params.require(:bitch_book_entry).permit(
      :topic,
      :title,
      :text,
      :rating,
      :user
    )
  end
end

app/controllers/dashboards_controller.rb
# app/controllers/dashboards_controller.rb

class DashboardsController < ApplicationController
  def index
    @nights = Night.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
    )
  end
end

app/controllers/games_controller.rb
# app/controllers/games_controller.rb

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @games = Game.search_by_city(params[:query])
    else
      @games = policy_scope(Game)
    end
  end

  def show; end

  def new
    @game = Game.new
    authorize @game
  end

  def create
    @game = Game.new(game_params)
    authorize @game
    @game.user = current_user
    if @game.save!
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to @game, notice: "Your amazing game is edited"
    else
      render :edit
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, notice: "Oh no! Bye bye to the amazing game 👋"
  end

  private

  def set_game
    @game = Game.find(params[:id])
    authorize @game
  end

  def game_params
    params.require(:game).permit(:language, :title, :description, :video, :category_id)
  end
end

app/controllers/nights_controller.rb
# app/controllers/nights_controller.rb

class NightsController < ApplicationController
  before_action :set_night, only: %i[show edit update destroy]

  def index
    @nights = Night.all
  end

  def new
    @night = Night.new
  end

  def create
    @night = Night.new(night_params)
    @night.user = current_user
    if @night.save!
      redirect_to nights_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @night.update(night_params)
    redirect_to night_path(@night)
  end

  def destroy
    @night.destroy
    redirect_to nights_path
  end

  private

  def set_night
    @night = Night.find(params[:id])
  end

  def night_params
    params.require(:night).permit(:start_time, :end_time, :user, :place_id, :title)
  end
end

app/controllers/pages_controller.rb
# app/controllers/pages_controller.rb

class PagesController < ApplicationController

  def home; end

  def about; end

  def contact; end
end

app/controllers/places_controller.rb
# app/controllers/places_controller.rb

class PlacesController < ApplicationController
  before_action :set_place, only: %i[show edit update destroy]

  def index
    # if params[:query].present?
    #   @query = params[:query]
    #   @places = Place.where("name ILIKE ?", "%#{params[:query]}%")
    # else
      @places = Place.all
    # end

    # The `geocoded` scope filters only places with coordinates
    @markers = @places.geocoded.map do |place| # ⬅️ Geocoding
      {
        lat: place.latitude,
        lng: place.longitude
      }
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)

    @place.user = current_user
    if @place.save
      redirect_to @place
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @place.update(place_params)
    redirect_to place_path(@place)
  end

  def destroy
    @place.destroy
    redirect_to places_path
  end

  private

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(
      :name,
      :address,
      :asshole_score,
      :barkeeper_rating,
      :dating_rating,
      :bathroom_rating,
      :beer_price,
      :user
    )
  end
end

app/controllers/profiles_controller.rb
# app/controllers/profiles_controller.rb

class ProfilesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(link_path)
    if current_page?(link_path)
      " focus-tab"
    else
      ""
    end
  end
end

app/views/bitch_book_entries/_form.html.erb
<%# app/views/bitch_book_entries/_form.html.erb %>

<%# TODO ************** %>

<%# ************** Create/Edit Bitch Book Entry ************** %>
<%= simple_form_for(@bitch_book_entry) do |f| %>
  <div class="form-inputs">
    <%= f.input :topic, placeholder: 'Whats the topic?🎉' %>
    <%= f.input :title, placeholder: 'Whats the title?🎉' %>
    <%= f.input :text, placeholder: 'Whats the text?🎉' %>
    <%= f.input :rating, placeholder: 'Whats the rating?' %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bitch_book_entries/edit.html.erb
<%# app/views/bitch_book_entries/edit.html.erb %>

<%# TODO ************** %>

<%# ************** Edit Bitch Book Entry ************** %>
<h1>Editing Bitch Book Entry</h1>

<%= render 'form', bitch_book_entry: @bitch_book_entry %>

<%= link_to 'Show', @bitch_book_entry %> |
<%= link_to 'Back', bitch_book_entries_path %>

app/views/bitch_book_entries/index.html.erb
<div class="p-5 mt-3">
  <h1 class="font-beta">The Bitchbook</h1>
    <div class="container p-5">
        <% @bitch_book_entries.each do |bitch_book_entry| %>
            <div class="card shadow h-100 py-2 p-5 m-4">
              <div class="list-name font-gamma">
                <%= bitch_book_entry.title %>
              </div>
                <div><%= link_to 'Show', bitch_book_entry, class: "btn" %></div>
                <div><%= link_to 'Edit', edit_bitch_book_entry_path(bitch_book_entry), class: "btn"  %></div>
                <div><%= link_to 'Destroy', bitch_book_entry, class: "btn", data: { "turbo-method": :delete, turbo_confirm: 'Are you sure? 🎱' } %></div>
            </div>
        <% end %>
    </div>
    <div class="p-3 m-4">
      <%= link_to 'New Bitch Book Entry', new_bitch_book_entry_path, class: "btn" %>
    </div>
</div>


<%# <#% if bitch_book_entry.approved?  %>
  <%#= link_to "Disapprove", approve_bitch_book_entry_path(bitch_book_entry), data: { "turbo-method": :patch }  %>
<%# <#% else %>
  <%#= link_to "Approve", approve_bitch_book_entry_path(bitch_book_entry), data: { "turbo-method": :patch }  %>
<%# <#% end %>

app/views/bitch_book_entries/new.html.erb
<%# app/views/bitch_book_entries/new.html.erb %>

<%# TODO ************** %>

<%# ************** New Bitch Book Entries ************** %>
<h1>New Bitch Book Entry</h1>

<%= render 'form', bitch_book_entry: @bitch_book_entry %>

<%= link_to 'Back', bitch_book_entries_path %>

app/views/bitch_book_entries/show.html.erb
<%#app/views/bitch_book_entries/show.html.erb%>

<%# TODO ************** %>
<%# Depending on Role you have different feutues here%>
<%# Feature Add Specific Comments, Role Admin, Player %>
<%# Feature Add Specific Rating, Role Admin, Player  %>

<%# ************** Display Specific Bitch Book Entry ************** %>
<div class="container bitch-book-entries">
<p id="notice"><%= notice %></p>
  <h1 class="font-alpha"><%= @bitch_book_entry.title %></h1>
    <div>
      <div class="container-bitch-book-entries">
        <div>
          <div class="list-name font-gamma"><%= @bitch_book_entry.text %></div>
          <%# <div class="list-name font-gamma"><%= @@bitch_book_entry.user %></div>
          <div class="item-btn font-gamma"><%= link_to 'All Bitchbook Entries', bitch_book_entries_path(@bitch_book_entry) %></div>
        </div>
    </div>
  <%= link_to 'Edit', edit_bitch_book_entry_path(@bitch_book_entry) %> |
  <%= link_to 'Back', bitch_book_entries_path %>
</div>

app/views/dashboards/overview.html.erb
<!-- app/views/dashboards/overview.html.erb -->

<h1>Dashboard</h1>
<section class="container-dashboard">
  <h1 class="font-alpha dashboard__title ">Hi, Player!</h1>
  <div class="sign-card--dashboard">
    <div class="tag2 tag--video">
      <h2 class="dashboard__video font-gamma">Your lastest Game</h2>
      <%# <% if current_user.signs != [] && current_user.signs.last.video.attached? %>
          <%# <p class="sign-name font-zeta"><%= current_user.signs.last.title %></p>
        <%# <div class="video-sign-container"> %>
          <%# <%= cl_video_tag(current_user.signs.last.video.key, :controls=>false, :autoplay=>true, :loop=>true, :muted=>true, :width=>220, :height=>150, class:"video")%>
        <%# </div> %>
      <%# <% else %>
       <%# <p class="sign-name">No signs yet</p> %>
       <%# <% end %>
        <%# <div class="sign-buttons">
        <%= link_to "New Sign", new_sign_path, class: "dashboard-button btn--normal" %>
      <%# </div> %>
    <%# </div> %>
    <%# <div class="tag2 tag--description"> %>
      <%# <div class="dashboard__texts"> %>
        <%# <h3 class="sign__display font-gamma">Your 5 favorite signs</h3> %>
        <%# <div class="bookmark-list"> %>
        <%# <% current_user.bookmarks.last(5).each do |bookmark| %>
          <%# <div class="bookmark-item"> %>
            <%# <%= link_to "#{bookmark.sign.title}", sign_path(bookmark.sign), class: "dashboard-button btn--normal" %>
          <%# </div> %>
        <%# <% end %>
        <%# </div> %>
      <%# </div> %>
    </div>
  </div>
</section>

app/views/games/edit.html.erb
<!-- app/views/games/edit.html.erb -->

<%# TODO ************** %>
<%# Create Edit Game Display %>

<%# ************** Edit Game ************** %>
<h1 class="font-beta">Games</h1>
<h1>Edit your Game</h1>

app/views/games/new.html.erb
<!-- app/views/games/new.html.erb -->

<%# TODO ************** %>

<%# ************** Create a new Game ************** %>
<h1>Create a new Game</h1>

app/views/nights/edit.html.erb
<%# app/views/nights/edit.html.erb %>

<%# TODO ************** %>
<%# Create Edit Night Display and make it pretty %>

<div class="container-places">
  <h1>Editing your Night</h1>
  <%= render 'form_night', place: @night %>
  <%= link_to 'Show', @night %> |
  <%= link_to 'Back', nights_path %>
</div>

app/views/nights/index.html.erb
<%#app/views/nights/index.html.erb%>
<h1 class="font-beta">Nights</h1>

<%# TODO ************** %>
<%# Create Nights Index Display %>
<%# Who will be able to add anything? %>
<%# Create Nights Footer? %>
<%# Create different nights %>
<%# Who can create different nights? The members? Strangers?%>

<%# ************** Display night cards ****** %>
  <div class="container">
    <div class="row justify-content-center">
      <% @nights.each do |night| %>
        <div class ="col-8 col-sm-6 col-md-4">
          <div class="card card-nbjb bg-light mb-3 mt-3">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1544281153-6603be88b354?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmlsbGlhcmRzfGVufDB8fDB8fA%3D%3D&w=1000&q=80" alt="Billard card image">
            <div class="card-body">
              <h5 class="card-text mb-1 text-xs font-gamma"> <%= night.title%></h5>
              <p class="card-text card-link mb-1 text-xs"> <%= link_to 'Show Night', night_path(night)%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<%# ************** Create new night ****** %>
<p class="card-text card-link mb-1 text-xs"> <%= link_to 'Add new night', new_night_path(@night)%></p>

app/views/nights/show.html.erb
<%#app/views/nights/show.html.erb%>

<h1 class="font-alpha">Your latest night was:</h1>
  <%# ************** Display Specific Night ************** %>
<div class="container">
  <p class="list-name font-gamma"><%= @night.title %></p>
  <p class="list-name font-gamma"><%= @night.place.name %></p>
  <p class="list-name font-gamma">The night started at: <%= @night.start_time %></p>

    <%# ************** Display the Games of the Night ****** %>
    <div class="container">
      <h3 class="font-alpha">There were <%= @night.games.count %> games played!</h3>
        <% @night.games.each_with_index do |game, index|%>
          <div class="item-btn btn font-gamma"><%= link_to "#{ index + 1 }. Game", game_path(game) %></div>
        <% end %>
    </div>
  <p class="list-name font-gamma">The night ended at: <%= @night.end_time %></p>
  <% if policy(@night).edit? %>
    <div class="item-btn btn font-gamma"><%= link_to "Edit Night", edit_night_path(@night)%></div>
  <% end %>
  <div class="item-btn font-gamma"><%= link_to 'All Nights', nights_path(@night) %></div>
</div>

app/views/places/index.html.erb
<%# app/views/places/index.html.erb %>
<div class="container-places">
  <h1 class="font-beta">Places</h1>
  <h2 class="font-gamma">Here is a list of all Places we played at:</h2>

  <div class="container">
    <div data-controller="map m-2"
        id="map"
        data-map-api-key-value="<%= ENV['NBJB_MAPBOX_API_KEY'] %>"
        style='width: 100%; height: 300px; border-radius: 15px;'>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <% @places.each_slice(2) do |places_row| %>
        <div class="row">
          <% places_row.each do |place| %>
            <div class="col-12 col-sm-6 mb-3">
              <div class="card bg-light mb-3 mt-3 border-left-primary shadow h-100 py-2">
                <img class="card-img-top" src="https://images.unsplash.com/photo-1544281153-6603be88b354?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmlsbGlhcmRzfGVufDB8fDB8fA%3D%3D&w=1000&q=80" alt="Billard card image">
                <div class="card-body">
                  <div class="card-text list-name mb-1 text-xs font-gamma"><%= place.name %></div>
                  <div class="card-text item-btn card-link mb-1 text-xs"><%= link_to 'Show Place', place_path(place) %></div>
                  <div><%= link_to 'Edit', edit_place_path(place) %></div>
                  <div><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="item-btn"><%= link_to 'Add new Place', new_place_path(@place) %></div>
</div>

app/views/places/show.html.erb
<%# app/views/places/show.html.erb %>
<div class="container-places">
  <%# ************** Display Specific Place ************** %>
  <h1 class="font-alpha">Your latest Place was:</h1>
    <div>
      <div class="container-places">
      <ol>
        <div><p class="font-gamma">Name: <%= @place.name %> </p></div>
        <div><p class="font-gamma">Address: <%= @place.address %> </p></div>
        <div><p class="font-gamma">Barkeeper: <%= @place.barkeeper_rating %>/8 <% @place.barkeeper_rating.to_i.times do  %><span>🎱</span><% end %></p></div><% @place.blank_balls.times do %><span class="glyphicon glyphicon-star-empty"></span><% end %>
        <div><p class="font-gamma">Average Beer Price: <%= @place.beer_price  %><% @place.beer_price.to_i.times do  %><span>🎱</span><% end %></p></div>
        <div><p class="font-gamma">Asshole Score: <%= @place.asshole_score %>/8 <% @place.asshole_score.to_i.times do  %><span>🎱</span><% end %></p></div>
        <div><p class="font-gamma">Dating Rating: <%= @place.dating_rating %>/8 <% @place.dating_rating.to_i.times do  %><span>🎱</span><% end %></p></div>
        <div><p class="font-gamma">Bathroom Rating: <%= @place.bathroom_rating %>/8 <% @place.bathroom_rating.to_i.times do  %><span>🎱</span><% end %></p></div>
        <div class="item-btn btn font-gamma"><%= link_to "Edit Place", edit_place_path(@place)%></div>
        <div class="item-btn btn font-gamma"><%= link_to 'All Places', places_path(@place) %></div>
      </ol>
    </div>
  </div>

app/views/profiles/index.html.erb
<h1 class="font-beta">Bitches</h1>
  <div class="container">
    <div class="row justify-content-center">
      <% @users.each do |user| %>
        <div class ="col-8 col-sm-6 col-md-4 m-4">
          <div class="card bg-light mb-3 mt-3 border-left-primary shadow h-100 py-2">
              <% if user.avatar.attached? %>
                <%= cl_image_tag user.avatar.key, height: 100, width: 400, crop: :fill, class: "card-img-top" %>
              <% else %>
                <img src="https://thumbs.dreamstime.com/b/user-woman-icon-lady-s-profile-female-web-sign-flat-art-object-black-white-silhouette-girl-business-suit-avatar-picture-173159996.jpg" alt="">
              <% end %>
            <div class="card-body">
              <div class="card-text list-name font-gamma"><%= link_to user.first_name, profile_path(user), class: "btn" %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/profiles/new.html.erb
<%# app/views/users/new.html.erb %>

<%# TODO ************** %>
<%# Create New User Display and make it pretty ♥️ %>

<div class="container py-5 form-adjust">
    <h1 class="font-alpha">Woo hoo new User</h1>
    <p class="font-gamma">Let's bring an amazing new User to your service</p>

  <%= render "form_user" %>
  <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/profiles/show.html.erb
<%# app/views/users/show.html.erb %>
<div class="container-users">
  <%# ************** Display Specific User ************** %>
  <h1 class="font-alpha">One of the Bitches</h1>
    <div>
      <div class="container">
      <ol>
        <div><p class="font-gamma">First Name: <%= @user.first_name %> </p></div>
        <div><p class="font-gamma">Last Name: <%= @user.last_name %> </p></div>
        <% if @user.avatar.attached? %>
          <%= cl_image_tag @user.avatar.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://thumbs.dreamstime.com/b/user-woman-icon-lady-s-profile-female-web-sign-flat-art-object-black-white-silhouette-girl-business-suit-avatar-picture-173159996.jpg" alt="">
        <% end %>
        <div><p class="font-gamma">Bio: <%= @user.bio %>
        <div><p class="font-gamma">Email: <%= @user.email %>
        <div><p class="font-gamma">Birthday: <%= @user.birthday  %>
        <div><p class="font-gamma">First Game: <%= @user.first_game %>
        <div><p class="font-gamma">Sign: <%= @user.sign %>
        <div><p class="font-gamma">Favorite Drink: <%= @user.favorite_drink %>
        <div><p class="font-gamma">Lucky Number: <%= @user.lucky_number %>
        <div><p class="font-gamma">Wins: <%= Player.where(user: current_user, winner: true).length %>
        <div><p class="font-gamma">Losses: <%= Player.where(user: current_user, winner: false).length %>
        <div class="item-btn btn font-gamma"><%= link_to 'All Bitches', profiles_path %></div>
      </ol>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "pool.png", :class => "navbar_home_image" %>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="font-gamma<%= active?(dashboards_path)%>">
        <%= link_to "HOME", dashboards_path, class: "btn-navbar"  %>
        </li>
        <li class="font-gamma<%= active?(profiles_path)%>">
          <%= link_to "BITCHES", profiles_path, class: "btn-navbar"  %>
        </li>
        <li class="font-gamma<%= active?(nights_path)%>">
          <%= link_to "NIGHTS", nights_path, class: "btn-navbar"  %>
        </li>
        <li class="font-gamma<%= active?(places_path)%>">
        <%= link_to "PLACES", places_path, class: "btn-navbar"  %>
        </li>
        <li class="font-gamma<%= active?(root_path)%>">
          <%= link_to "BITCHBOOK", bitch_book_entries_path, class: "btn-navbar"  %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", root_path, class: "dropdown-item" %>
            <%= link_to "Plan Night", new_night_path, class: "dropdown-item" %>
            <%= link_to "All Nights", nights_path, class: "dropdown-item" %>
            <%= link_to "Places", places_path, class: "dropdown-item" %>
            <%= link_to "Bitches", profiles_path, class: "dropdown-item" %>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<%# app/views/users/index.html.erb %>
<div class="container-users">
  <h1 class="font-beta">Bitches</h1>

  <%# ************** Display Users/Bitches ************** %>
  <div class="container">
    <div class="row justify-content-center">
      <% @users.each do |user| %>
        <div class ="col-8 col-sm-6 col-md-4 m-4">
          <div class="card card-nbjb bg-light mb-3 mt-3 border-left-primary shadow h-100 py-2">
            <img class="card-img-top" src="https://images.unsplash.com/photo-1544281153-6603be88b354?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmlsbGlhcmRzfGVufDB8fDB8fA%3D%3D&w=1000&q=80" alt="Billard card image">
            <div class="card-body">
              <div class="card-text list-name mb-1 text-xs font-gamma"><%= link_to user.first_name, user_path(user)  %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="item-btn"><%= link_to 'Add new User', new_user_path(@user) %></div>
</div>

app/views/users/show.html.erb
<%# app/views/users/show.html.erb %>
<div class="container-users">
  <%# ************** Display Specific User ************** %>
  <h1 class="font-alpha">One of the Bitches</h1>
    <div>
      <div class="container-places">
      <ol>
        <div><p class="font-gamma">First Name: <%= @user.first_name %> </p></div>
        <div><p class="font-gamma">Last Name: <%= @user.last_name %> </p></div>
        <% if @user.avatar.attached? %>
          <%= cl_image_tag @user.avatar.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://thumbs.dreamstime.com/b/user-woman-icon-lady-s-profile-female-web-sign-flat-art-object-black-white-silhouette-girl-business-suit-avatar-picture-173159996.jpg" alt="">
        <% end %>
        <div><p class="font-gamma">Bio: <%= @user.bio %>
        <div><p class="font-gamma">Email: <%= @user.email %>
        <div><p class="font-gamma">Birthday: <%= @user.birthday  %>
        <div><p class="font-gamma">First Game: <%= @user.first_game %>
        <div><p class="font-gamma">Sign: <%= @user.sign %>
        <div><p class="font-gamma">Favorite Drink: <%= @user.favorite_drink %>
        <div><p class="font-gamma">Lucky Number: <%= @user.lucky_number %>
        <div><p class="font-gamma">Wins: <%= Player.where(user: current_user, winner: true).length %>
        <div><p class="font-gamma">Losses: <%= Player.where(user: current_user, winner: false).length %>
        <div class="item-btn btn font-gamma"><%= link_to 'All Bitches', users_path(@user) %></div>
      </ol>
    </div>
  </div>